### ISSUE TITLE
Relative links are being stripped

### ISSUE THREAD

**Issue by hyungjs** [mapbox/sanitize-caja#5]
Is there a reason why relative links get sanitized?

https://tonicdev.com/56e6eaf2101fca12006c79e9/56e6eca31a1eb7110014b44f

**Comment by tmcw** [comment]
Yes, see [the cleanUrl method](https://github.com/mapbox/sanitize-caja/blob/master/index.js#L9).  URLs are required to have a protocol, and relative links don't have protocols.
