### ISSUE TITLE
Publish New Version

### ISSUE THREAD

**Issue by eltonjuan** [mapbox/sanitize-caja#8]
It looks like this module hasn't been published in a while. Specifically, I am running into issues with Webpack is throwing because Octal literals in strict mode are invalid... This commit (https://github.com/mapbox/sanitize-caja/commit/d84a7b11c3cdbbb0a8f0c433cee36d705e18df48) was made to correct the issue, but the latest version in NPM does not reflect this change. 

The change above was made 2 months ago, while the most recent publish was over a year ago in NPM. If you could, please release a new version of this module so that I don't have to work off of a fork... 

Thanks!

**Comment by eltonjuan** [comment]
Also, if you could tick the dependency in https://www.github.com/mapbox/mapbox.js while you're at it, that would be great!

**Comment by tmcw** [comment]
Published sanitize-caja@0.1.4
